USE QLKS;

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CKC_NGAY_DEN_NGAY_DI')
	ALTER TABLE CHI_TIET_DAT_PHONG
	DROP CONSTRAINT CKC_NGAY_DEN_NGAY_DI

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CKC_NGAY_NHAN_PHONG_NGAY_TRA_PHONG')
	ALTER TABLE PHIEU_THUE_PHONG
	DROP CONSTRAINT CKC_NGAY_NHAN_PHONG_NGAY_TRA_PHONG

ALTER TABLE CHI_TIET_DAT_PHONG
ADD CONSTRAINT CKC_NGAY_DEN_NGAY_DI CHECK(NGAY_DEN <= NGAY_DI);

ALTER TABLE PHIEU_THUE_PHONG
ADD CONSTRAINT CKC_NGAY_NHAN_PHONG_NGAY_TRA_PHONG CHECK(NGAY_NHAN_PHONG <= NGAY_TRA_PHONG);

