USE QLKS;

IF EXISTS(SELECT 1 FROM sys.objects WHERE type = 'FN')
	DROP FUNCTION FN_GENERATE_ROOM_NUMBER
GO

-- This function is used for auto-creating room number (go with TRIGGER_GENERATE_ROOT_NUMBER)
CREATE FUNCTION FN_GENERATE_ROOM_NUMBER(@ID INT)
RETURNS NVARCHAR(6) 
AS 
BEGIN 
RETURN 'PH' + RIGHT('00000' + CONVERT(VARCHAR(6), @ID), 4)
END
GO