USE QLKS;

IF EXISTS(SELECT 1 FROM sys.objects WHERE type = 'FN')
	DROP FUNCTION FN_DOES_THIS_EMPLOYEE_EXIST
GO

IF EXISTS(SELECT 1 FROM sys.objects WHERE type = 'FN')
	DROP FUNCTION FN_GENERATE_ROOM_NUMBER
GO

CREATE FUNCTION FN_DOES_THIS_EMPLOYEE_EXIST
(
@USERNAME NVARCHAR(50),
@PASSWORD NVARCHAR(20)
)
RETURNS BIT
AS
BEGIN
DECLARE @FLAG BIT
IF EXISTS(SELECT * FROM THU_NGAN WHERE TEN_DANG_NHAP = @USERNAME AND MAT_KHAU = @PASSWORD)
	SET @FLAG = 1
ELSE
	SET @FLAG = 0
RETURN @FLAG
END
GO

-- This function is used for auto-creating room number (go with TRIGGER_GENERATE_ROOT_NUMBER)
CREATE FUNCTION FN_GENERATE_ROOM_NUMBER(@ID INT)
RETURNS NVARCHAR(6) 
AS 
BEGIN 
RETURN 'PH' + RIGHT('00000' + CONVERT(VARCHAR(6), @ID), 4)
END
GO