USE QLKS;

IF EXISTS(SELECT 1 FROM sys.server_principals WHERE name = 'QLKS_ADMIN')
	DROP LOGIN QLKS_ADMIN

IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name = 'QLKS_ADMIN')
	DROP USER QLKS_ADMIN

IF EXISTS(SELECT 1 FROM sys.server_principals WHERE name = 'QLKS_NHAN_VIEN')
	DROP LOGIN QLKS_NHAN_VIEN

IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name = 'QLKS_NHAN_VIEN')
	DROP USER QLKS_NHAN_VIEN

----------- create user QLKS_ADMIN and grant privileges for QLKS_ADMIN -----------
CREATE LOGIN QLKS_ADMIN WITH PASSWORD = '1234', DEFAULT_DATABASE = QLKS
CREATE USER QLKS_ADMIN FOR LOGIN QLKS_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_DANG_KY_DICH_VU TO QLKS_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DICH_VU TO QLKS_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_THUE_PHONG TO QLKS_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHONG TO QLKS_ADMIN

----------- create user QLKS_NHAN_VIEN and grant privileges for QLKS_NHAN_VIEN -----------
CREATE LOGIN QLKS_NHAN_VIEN WITH PASSWORD = '1234', DEFAULT_DATABASE = QLKS
CREATE USER QLKS_NHAN_VIEN FOR LOGIN QLKS_NHAN_VIEN
GRANT SELECT, INSERT, UPDATE ON OBJECT::PHIEU_DANG_KY_DICH_VU TO QLKS_NHAN_VIEN
GRANT SELECT, INSERT, UPDATE ON OBJECT::DICH_VU TO QLKS_NHAN_VIEN
GRANT SELECT, INSERT, UPDATE ON OBJECT::PHIEU_THUE_PHONG TO QLKS_NHAN_VIEN