USE QLKS;

IF EXISTS(SELECT 1 FROM sys.server_principals WHERE name = 'ADMIN')
	DROP LOGIN ADMIN

IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name = 'ADMIN')
	DROP USER ADMIN

IF EXISTS(SELECT 1 FROM sys.server_principals WHERE name = 'NHAN_VIEN')
	DROP LOGIN NHAN_VIEN

IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name = 'NHAN_VIEN')
	DROP USER NHAN_VIEN

----------- create user QLKS_ADMIN and grant privileges for QLKS_ADMIN -----------
CREATE LOGIN ADMIN WITH PASSWORD = '1234', DEFAULT_DATABASE = QLKS
CREATE USER ADMIN FOR LOGIN ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_DANG_KY_DICH_VU TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DICH_VU TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_THUE_PHONG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHONG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::KHACH_HANG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::QUOC_GIA TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::LOAI_PHONG TO ADMIN
GRANT EXECUTE ON OBJECT::SP_PHIEU_DANG_KY_DICH_VU_THEO_SO_PHONG TO ADMIN
GRANT EXECUTE ON OBJECT::SP_PHIEU_DANG_KY_DICH_VU TO ADMIN
GRANT EXECUTE ON OBJECT::SP_DICH_VU TO ADMIN

----------- create user QLKS_NHAN_VIEN and grant privileges for QLKS_NHAN_VIEN -----------
CREATE LOGIN NHAN_VIEN WITH PASSWORD = '1234', DEFAULT_DATABASE = QLKS
CREATE USER NHAN_VIEN FOR LOGIN NHAN_VIEN
GRANT SELECT, INSERT, UPDATE ON OBJECT::PHIEU_DANG_KY_DICH_VU TO NHAN_VIEN
GRANT SELECT, INSERT, UPDATE ON OBJECT::DICH_VU TO NHAN_VIEN
GRANT SELECT, INSERT, UPDATE ON OBJECT::PHIEU_THUE_PHONG TO ADMIN