USE QLKS;

IF EXISTS(SELECT 1 FROM sys.server_principals WHERE name = 'ADMIN')
	DROP LOGIN ADMIN

IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name = 'ADMIN')
	DROP USER ADMIN

----------- create user QLKS_ADMIN and grant privileges for QLKS_ADMIN -----------
CREATE LOGIN ADMIN WITH PASSWORD = '1234', DEFAULT_DATABASE = QLKS

-- this login is allowed to create and alter databases
EXEC sp_addsrvrolemember 'ADMIN', 'dbcreator'

CREATE USER ADMIN FOR LOGIN ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_DANG_KY_DICH_VU TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DICH_VU TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_THUE_PHONG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHONG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::KHACH_HANG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::QUOC_GIA TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::LOAI_PHONG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::TINH_TRANG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::CONG_TY TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DOAN_KHACH TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::KHACH_TRO TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_THU_KHACH_HANG TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::PHIEU_THU_DOAN_KHACH TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::THU_NGAN TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::ADMINS TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::QUYEN TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::QUYEN_THU_NGAN TO ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::QUYEN_ADMIN TO ADMIN

GRANT EXECUTE ON OBJECT::SP_INSERT_SERVICE_ORDER_BILL TO ADMIN
GRANT EXECUTE ON OBJECT::FN_DOES_THIS_EMPLOYEE_EXIST TO ADMIN