USE QLKS;

IF EXISTS(SELECT 1 FROM sys.objects WHERE type = 'TR')
	DROP TRIGGER TR_PHONG_INSERT
GO

-- This trigger is used to create room number (go with FN_GENERATE_ROOM_NUMBER)
CREATE TRIGGER TR_PHONG_INSERT ON PHONG AFTER INSERT 
AS 
UPDATE PHONG 
SET PHONG.SO_PHONG = dbo.FN_GENERATE_ROOM_NUMBER(PHONG.MA_PHONG) 
FROM PHONG INNER JOIN INSERTED ON PHONG.MA_PHONG = INSERTED.MA_PHONG
GO