USE QLKS;

IF EXISTS(SELECT 1 FROM sys.objects WHERE type = 'TR')
	DROP TRIGGER TR_PHIEU_THUE_PHONG
GO

IF EXISTS(SELECT 1 FROM sys.objects WHERE type = 'TR')
	DROP TRIGGER TR_PHONG_INSERT
GO

-- This trigger is used to create room number (go with FN_GENERATE_ROOM_NUMBER)
CREATE TRIGGER TR_PHONG_INSERT ON PHONG AFTER INSERT 
AS 
UPDATE PHONG 
SET PHONG.SO_PHONG = dbo.FN_GENERATE_ROOM_NUMBER(PHONG.MA_PHONG) 
FROM PHONG INNER JOIN INSERTED ON PHONG.MA_PHONG = INSERTED.MA_PHONG
GO

-- This trigger is used to fill DA_TRA_PHONG after SET NGAY_TRA_PHONG
CREATE TRIGGER TR_PHIEU_THUE_PHONG ON PHIEU_THUE_PHONG AFTER UPDATE 
AS
BEGIN

IF EXISTS(SELECT 1 FROM PHIEU_THUE_PHONG A INNER JOIN DELETED B ON A.MA_PHIEU = B.MA_PHIEU WHERE A.NGAY_TRA_PHONG IS NOT NULL)
BEGIN
	UPDATE PHIEU_THUE_PHONG 
	SET PHIEU_THUE_PHONG.DA_TRA_PHONG = 1
	FROM PHIEU_THUE_PHONG A INNER JOIN DELETED B ON A.MA_PHIEU = B.MA_PHIEU
END
ELSE
BEGIN
	UPDATE PHIEU_THUE_PHONG 
	SET PHIEU_THUE_PHONG.DA_TRA_PHONG = 0
	FROM PHIEU_THUE_PHONG A INNER JOIN DELETED B ON A.MA_PHIEU = B.MA_PHIEU
END
END
GO

--CREATE TRIGER TR_PHIEU_THUE_PHONG ON PHIEU_THUE_PHONG AFTER INSERT
--AS
--BEGIN
--END